version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    container_name: elasticsearch
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  arc:
    build: ./
    container_name: arc
    restart: on-failure
    environment:
    - ES_CLUSTER_URL=http://elasticsearch:9200
    - USERNAME=foo
    - PASSWORD=bar
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
