version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=http://localhost:8000
      - -Ebootstrap.memory_lock=true
    user: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure

  arc:
    image: siddharthlatest/arc:latest
    container_name: arc
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    restart: on-failure
    links:
      - elasticsearch